
x-airflow-common: &airflow-common
  build:
    context: .
    dockerfile: Dockerfile.airflow
  environment:
    AIRFLOW__CORE__EXECUTOR: LocalExecutor
    AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://postgres:password@postgres/airflow_meta
    AIRFLOW__CORE__LOAD_EXAMPLES: 'false'
    AIRFLOW__CORE__FERNET_KEY: ''
    AIRFLOW__WEBSERVER__SECRET_KEY: 'football_pipeline_secret'
    DB_HOST: postgres
    DB_PORT: 5432
    DB_NAME: football_oltp
    DB_USER: postgres
    DB_PASSWORD: password
    DWH_DB_NAME: football_dwh
  volumes:
    - ./dags:/opt/airflow/dags
    - ./pipeline:/opt/airflow/pipeline
    - ./data:/opt/airflow/data
    - ./logs:/opt/airflow/logs
    - ./sql:/opt/airflow/sql
  depends_on:
    - postgres

services:
  postgres:
    image: postgres:16
    container_name: football_pg
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: football_oltp
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  airflow-init:
    <<: *airflow-common
    entrypoint: /bin/bash
    command:
      - -c
      - |
        airflow db migrate
        airflow users create --username admin --password admin --firstname Admin --lastname User --role Admin --email admin@example.com || true

  airflow-webserver:
    <<: *airflow-common
    command: webserver
    ports:
      - "8081:8080"
    depends_on:
      - airflow-init

  airflow-scheduler:
    <<: *airflow-common
    command: scheduler
    depends_on:
      - airflow-init

  metabase:
    image: metabase/metabase:latest
    container_name: football_metabase
    ports:
      - "3000:3000"
    depends_on:
      - postgres

volumes:
  pgdata:

